const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL:
    "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",

  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAIL: "FETCH_POSITION_FAIL",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_FAIL: "SAVE_USER_FAIL",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",

  EDIT_SPECIALTY_SUCCESS: "EDIT_SPECIALTY_SUCCESS",
  EDIT_SPECIALTY_FAIL: "EDIT_SPECIALTY_FAIL",

  EDIT_CLINIC_SUCCESS: "EDIT_CLINIC_SUCCESS",
  EDIT_CLINIC_FAIL: "EDIT_CLINIC_FAIL",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAIL: "FETCH_ALL_USER_FAIL",

  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAIL: "FETCH_TOP_DOCTOR_FAIL",

  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAIL: "FETCH_ALL_DOCTOR_FAIL",

  SAVE_DETAIL_DOCTOR_SUCCESS: "SAVE_DETAIL_DOCTOR_SUCCESS",
  SAVE_DETAIL_DOCTOR_FAIL: "SAVE_DETAIL_DOCTOR_FAIL",

  FETCH_ALLCODE_SCHEDULE_HOUR_SUCCESS:
    "FETCH_ALLCODE_SCHEDULE_HOUR_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_HOUR_FAIL:
    "FETCH_ALLCODE_SCHEDULE_HOUR_FAIL",

  FETCH_DOCTOR_INFOR_START: "FETCH_DOCTOR_INFOR_START",
  FETCH_DOCTOR_INFOR_SUCCESS: "FETCH_DOCTOR_INFOR_SUCCESS",
  FETCH_DOCTOR_INFOR_FAIL: "FETCH_DOCTOR_INFOR_FAIL",

  FETCH_ALL_SPECIALTY_SUCCESS:
    "FETCH_ALL_SPECIALTY_SUCCESS",
  FETCH_ALL_SPECIALTY_FAIL: "FETCH_ALL_SPECIALTY_FAIL",
  DELETE_SPE_SUCCESS: "DELETE_SPE_SUCCESS",
  DELETE_SPE_FAIL: "DELETE_SPE_FAIL",

  DELETE_CLI_SUCCESS: "DELETE_CLI_SUCCESS",
  DELETE_CLI_FAIL: "DELETE_CLI_FAIL",

  SAVE_SPECIALTY_SUCCESS: "SAVE_SPECIALTY_SUCCESS",
  SAVE_SPECIALTY_FAIL: "SAVE_SPECIALTY_FAIL",

  SAVE_CLINIC_SUCCESS: "SAVE_CLINIC_SUCCESS",
  SAVE_CLINIC_FAIL: "SAVE_CLINIC_FAIL",

  FETCH_ALL_CLINIC_SUCCESS: "FETCH_ALL_CLINIC_SUCCESS",
  FETCH_ALL_CLINIC_FAIL: "FETCH_ALL_CLINIC_FAIL",

  EDIT_HANDBOOK_SUCCESS: "EDIT_HANDBOOK_SUCCESS",
  EDIT_HANDBOOK_FAIL: "EDIT_HANDBOOK_FAIL",

  FETCH_ALL_HANDBOOK_SUCCESS: "FETCH_ALL_HANDBOOK_SUCCESS",
  FETCH_ALL_HANDBOOK_FAIL: "FETCH_ALL_HANDBOOK_FAIL",

  SAVE_HANDBOOK_SUCCESS: "SAVE_HANDBOOK_SUCCESS",
  SAVE_HANDBOOK_FAIL: "SAVE_HANDBOOK_FAIL",
});

export default actionTypes;
